-- HR DB 資料查詢
-- 查詢每個部門高於平均部門薪資的員工
-- 1.平均部門薪資
-- 2.高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)

-- SQL 練習題(四)
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID,
	AVG_D.DEPARTMENT_ID, AVG_D.DEP_AVG_SALARY
FROM employees E JOIN (
	-- 平均部門薪資表
	SELECT DEPARTMENT_ID, FLOOR(AVG(SALARY)) DEP_AVG_SALARY
	FROM employees
	GROUP BY DEPARTMENT_ID
) AVG_D 
ON E.DEPARTMENT_ID = AVG_D.DEPARTMENT_ID
WHERE E.SALARY > AVG_D.DEP_AVG_SALARY
ORDER BY AVG_D.DEP_AVG_SALARY DESC, E.SALARY DESC;

-- WITH (Common Table Expressions)
WITH AVG_D AS (
	-- 平均部門薪資表
	SELECT DEPARTMENT_ID, FLOOR(AVG(SALARY)) DEP_AVG_SALARY
	FROM employees
	GROUP BY DEPARTMENT_ID
)
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, D.DEPARTMENT_NAME,
	AVG_D.DEPARTMENT_ID, AVG_D.DEP_AVG_SALARY
FROM employees E 
	JOIN AVG_D ON E.DEPARTMENT_ID = AVG_D.DEPARTMENT_ID
	JOIN departments D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY > AVG_D.DEP_AVG_SALARY
ORDER BY AVG_D.DEP_AVG_SALARY DESC, E.SALARY DESC;

